### ISSUE TITLE
macOS: Not running

### ISSUE THREAD

**Issue by m0urao** [bryanberger/figma-discord-presence#12]
Hi, 
I can't run this on macOS because Apple cannot check for malicious software.
Any updates on when this will be solved?

**Comment by bryanberger** [comment]
@m0urao Can you supply more information?

- macOS version
- Figma version
- screenshot of any error(s)

**Comment by m0urao** [comment]
@bryanberger sorry for the delay!

- 13.3.1 
- 116.8.5

<img width="264" alt="Screenshot 2023-05-11 at 12 28 59" src="https://github.com/bryanberger/figma-discord-presence/assets/91987141/c6ce0127-af0c-443e-89c0-86d76cad50f0">

**Comment by m0urao** [comment]
@bryanberger any updates on this?

**Comment by N3v1** [comment]
@bryanberger Also doesn't work for me 

- MacOS: Sonoma RC2 & 13.5
- Figma: newest

cc: @m0urao

**Comment by bryanberger** [comment]
@N3v1, @m0urao try downloading the latest version https://github.com/bryanberger/figma-discord-presence/releases/tag/v1.2.6

**Comment by m0urao** [comment]
@bryanberger Works! Thanks 😄
