### ISSUE TITLE
I is possible to change the name "Figma" to something else in the rich presence? 

### ISSUE THREAD

**Issue by NextPr0gram** [bryanberger/figma-discord-presence#16]

**Comment by bryanberger** [comment]
@NextPr0gram what did you have in mind?

**Comment by NextPr0gram** [comment]
Erm.. "Figma balls".
I'm using a custom rpc plugin to do it but it would be cool if i can do it in the program since it also show what I'm actually working on in the rich presence.

**Comment by bryanberger** [comment]
@NextPr0gram nah probably not something I'd add lol, feel free to fork.
